### ISSUE TITLE
Getting an error on OSX with 3.1

### ISSUE THREAD

**Issue by dabeeeenster** [yaybu/yaybu#117]
```
➜  ~/projects/yaybu yaybu up
[*] Testing compute credentials/connectivity
[ ] Creating node ''test_at_ec2''...
Traceback (most recent call last):
  File "/Applications/Yaybu.app/Contents/Resources/__boot__.py", line 37, in <module>
    _run()
  File "/Applications/Yaybu.app/Contents/Resources/__boot__.py", line 32, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Yaybu.app/Contents/Resources/YaybuShell.py", line 19, in <module>
    main()
  File "yaybu/core/main.pyc", line 77, in main
  File "yaybu/core/main.pyc", line 70, in _main
  File "yaybu/core/command.pyc", line 70, in onecmd
  File "yaybu/core/command.pyc", line 306, in do_up
  File "yay/config.pyc", line 67, in resolve
  File "yay/ast.pyc", line 220, in resolve
  File "yay/ast.pyc", line 563, in resolve_once
  File "yay/ast.pyc", line 563, in <genexpr>
  File "yay/ast.pyc", line 220, in resolve
  File "yay/ast.pyc", line 716, in resolve_once
  File "yaybu/base.pyc", line 32, in resolve
  File "yay/ast.pyc", line 220, in resolve
  File "yay/ast.pyc", line 716, in resolve_once
  File "yay/ast.pyc", line 239, in expand
  File "yay/ast.pyc", line 2639, in expand_once
  File "yaybu/provisioner/part.pyc", line 51, in apply
  File "yay/ast.pyc", line 651, in as_string
  File "yay/ast.pyc", line 239, in expand
  File "yay/ast.pyc", line 822, in expand_once
  File "yay/ast.pyc", line 239, in expand
  File "yay/ast.pyc", line 1421, in expand_once
  File "yay/ast.pyc", line 2633, in get_key
  File "yaybu/compute/part.pyc", line 242, in apply
  File "yaybu/compute/part.pyc", line 142, in _get_size
  File "yaybu/core/util.pyc", line 43, in __call__
  File "yaybu/compute/part.pyc", line 95, in sizes
  File "libcloud/compute/drivers/ec2.pyc", line 642, in list_sizes
  File "libcloud/compute/base.pyc", line 949, in _get_size_price
  File "libcloud/pricing.pyc", line 122, in get_size_price
  File "libcloud/pricing.pyc", line 74, in get_pricing
IOError: [Errno 20] Not a directory: '/Applications/Yaybu.app/Contents/Resources/lib/python2.7/site-packages.zip/libcloud/data/pricing.json'
2013-11-07 13:20:49.302 yaybu[39771:507] Yaybu Error
```

My Yaybufile:

```
  new Provisioner as instance1:
      new Compute as server:
          driver:
              id: EC2
              key: xxxx
              secret: xxxx

          image: ami-57afb223
          size: m1.micro
          name: test_at_ec2

          user: root
          password: aez5Eep4

      resources:
          - User:
              name: django
```

**Comment by Jc2k** [comment]
Hi there. Thanks for the detailed bug report! I'm looking at this now.

It's specific to the binary build, so i'm going to fix it at the bundle building layer hopefully.

**Comment by dabeeeenster** [comment]
Great thanks. How easy is it for me to roll my own build?

---

Ben Rometsch - Director
Solid State Group
Tel: +44 (0)20 7613 7223
From: John Carr John Carr
Reply: yaybu/yaybu reply@reply.github.com
Date: 7 November 2013 at 14:05:57
To: yaybu/yaybu yaybu@noreply.github.com
Subject:  Re: [yaybu] Getting an error on OSX with 3.1 (#117)  
Hi there. Thanks for the detailed bug report! I'm looking at this now.

It's specific to the binary build, so i'm going to fix it at the bundle building layer hopefully.

**Comment by Jc2k** [comment]
It's not too bad, but i'm hoping to release `3.1.1` tonight if you arent in a rush. I had hoped to have pushed it out already, but this has flushed out a few other validation gremlins that I need to fix - it looks like that AMI doesnt exist any more and i'm doing a rubbish job of handling that.

**Comment by dabeeeenster** [comment]
Great thanks - no rush!

---

Ben Rometsch
Director - Solid State Group
flavours.me/dabeeeenster
www.solidstategroup.com

**Comment by Jc2k** [comment]
I've just pushed new binary packages to the releases page and updated docs.yaybu.com.

This includes the pricing.json fix plus better validation of some of the `Compute` settings.

I think you'll need to tweak your Yaybufile before it will work - the AMI no longer exists, it's `t1.micro` not `m1.micro` and until our libcloud patches are released you need to specify ex_keyname like here http://yaybu.readthedocs.org/en/3.1.1/compute.html#ec2.

I'm not sure which region you'll get if you use `EC2` as your driver id. You can use `EC2_EU_WEST` to get an instance in Ireland.

Let me know how you get on!

**Comment by dabeeeenster** [comment]
Great thanks will have a play
