### ISSUE TITLE
Traceback when running `yaybu ssh foo`

### ISSUE THREAD

**Issue by mitchellrj** [yaybu/yaybu#135]
```
    Traceback (most recent call last):
      File "/usr/bin/yaybu", line 9, in <module>
        load_entry_point('Yaybu==3.1.1', 'console_scripts', 'yaybu')()
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yaybu/core/main.py", line 77, in main
        _main(argv)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yaybu/core/main.py", line 70, in _main
        sys.exit(com.onecmd(" ".join(args)) or 0)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yaybu/core/command.py", line 70, in onecmd
        return func(opts, args)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yaybu/core/command.py", line 346, in do_ssh
        node = graph.parse_expression(args[0])
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yay/config.py", line 59, in parse_expression
        node = p.parse(expression)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yay/parser.py", line 96, in parse
        lexer=self.lexer(source=source),
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yay/lexer.py", line 490, in __init__
        debug, optimize, lextab, reflags, source)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yay/lexer.py", line 47, in __init__
        outputdir=os.path.dirname(__file__))
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/ply/lex.py", line 1005, in lex
        lexobj.writetab(lextab,outputdir)
      File "/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/ply/lex.py", line 177, in writetab
        tf = open(filename,"w")
    IOError: [Errno 13] Permission denied: '/usr/share/python/python-yaybu/local/lib/python2.7/site-packages/yay/lextab.py'
```

**Comment by Jc2k** [comment]
Ugh. Subclasses of ply lexer/parsers end up fighting over generated cached files that ship in our binaries. Refactored to avoid subclassing ply things.
